server:
  port: 7081
spring:
  application:
    name: demo-zuul-gateway
  main:
    allow-bean-definition-overriding: true
demo:
  eureka:
    url: http://127.0.0.1:7080/eureka/ #固定写法，eureka为服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: ${demo.eureka.url}
zuul:
  routes:
    api-user:
      path: /service-user/**
      service-id: demo-service-user
    api-order:
      path: /service-order/**
      service-id: demo-service-order